### ISSUE TITLE
Chrome bug when I use angular-youtube-embed

### ISSUE THREAD

**Issue by stanislavche** [brandly/angular-youtube-embed#104]
http://joxi.ru/a2XJ6BfyVX7Wrg
Site work, but this error in console let me panic

**Comment by aluanhaddad** [comment]
This is actually not a bug Angular YouTube Embed plugin at all. You'll get the same errors if you use the YouTube iframe API directly, with or without angular. It's a known issue in chrome that, from my reading, I do not believe they intend to fix.

**Comment by brandly** [comment]
@aluanhaddad is right! there's some more info here: https://github.com/brandly/angular-youtube-embed/issues/67
