### ISSUE TITLE
Doesn't work with ?rel=0

### ISSUE THREAD

**Issue by bersling** [brandly/angular-youtube-embed#105]
For embedding youtube videos, a useful option is **?rel=0** at the end of the embed code. This prevents suggestions of other videos once the video is done playing. However, when I put a url containing ?rel=0, other videos are suggested anyways.

**Comment by brandly** [comment]
put 

```js
$scope.playerVars = {
  rel: 0
}
```

as a part of your `player-vars`. [read more here](https://github.com/brandly/angular-youtube-embed#player-parameters) :star:
