### ISSUE TITLE
Unable to install embed getting package issue

### ISSUE THREAD

**Issue by scoopstalk** [brandly/angular-youtube-embed#111]
$ npm install --save angular-youtube-embed
npm WARN package.json youtubevideo@1.1.1 No repository field.
npm WARN package.json youtubevideo@1.1.1 No README data
npm WARN package.json youtubevideo@1.1.1 No license field.
angular-youtube-embed@1.1.1 node_modules\angular-youtube-embed
└── angular@1.5.3

how to sort this issue?

**Comment by brandly** [comment]
looks like it worked!

it appears _your_ package is called `youtubevideo` and has a poorly formatted `package.json`, so `npm` is showing you some warnings. if you want those warnings to go away, then add a repository field, README data, and license field. read more here: https://docs.npmjs.com/files/package.json
