### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR When video is paused 

### ISSUE THREAD

**Issue by SivarajParamasivam** [brandly/angular-youtube-embed#114]
I am getting the following error when I paused the youtube video.

GET https://pagead2.googlesyndication.com/pagead/gen_204?rt=adsense&lid=17&e=265944523&id&c=1141502247177130&domain=localhost net::ERR_QUIC_PROTOCOL_ERROR

**Comment by AtomSub** [comment]
From: https://productforums.google.com/d/msg/chrome/xKFfhDvhjU8/lqMvuQzhfQoJ
1. Go to chrome://flags/ in Google Chrome
2. Find "Experimental QUIC protocol" (CTRL+F, Write QUIC in the search­field)
3. Set it to "Disabled"
4. Close and restart Chrome (Might not be needed, but just to be sure)

**Comment by brandly** [comment]
thanks @AtomSub!
