### ISSUE TITLE
Start the video in fullscreen

### ISSUE THREAD

**Issue by VaVoVo** [brandly/angular-youtube-embed#123]
Hi,

how can i start the YouTube video direct in fullscreen?

kind regards, thx

**Comment by brandly** [comment]
sorry for not getting back to you sooner! are you using a mobile device? the `playsinline` option might be what you're looking for. you'd pass that into `player-vars` [as shown here](https://github.com/brandly/angular-youtube-embed#player-parameters). good luck! 🌟
