### ISSUE TITLE
player is not defined

### ISSUE THREAD

**Issue by ezazwar1** [brandly/angular-youtube-embed#124]
i tried to close video function but that doesnt seem to be working

player is not defined  error is thrown

**Comment by brandly** [comment]
could you make a [JSFiddle](https://jsfiddle.net/) or something similar to show what code produces the error?

the `player` gets defined asynchronously, so there's a chance you're trying to access a method on it before it's define. it's best to wait for a `youtube.player.ready` event, [as documented here](https://github.com/brandly/angular-youtube-embed#events-and-player-controls), before accessing the player object.

**Comment by brandly** [comment]
if this error is reproducible, let me know! i'm closing this in the meantime, until there's some example code to work with 🎆
