### ISSUE TITLE
Can we autoplay and mute ?

### ISSUE THREAD

**Issue by darkterra** [brandly/angular-youtube-embed#125]
Hi, a big thank for your job !!

I would like auto play a youtube vidéo, but I think it 'll become irritate after some time. So I look for a option 'playerVars' like mute or sound or volume, but I have not found anything.

Maybe I missed something?

**Comment by brandly** [comment]
i just took a look, and it doesn't appear that you can mute the video with player vars.

however, in your controller, you could [listen for an event](https://github.com/brandly/angular-youtube-embed#events-and-player-controls) and [mute the player](https://developers.google.com/youtube/iframe_api_reference#Playback_controls) once it's ready

```js
$scope.$on('youtube.player.ready', function ($event, player) {
  player.mute()
})
```

i haven't actually tested this code, but i believe it should work. good luck! 🌟

**Comment by darkterra** [comment]
Great !

Thank you so mutch !

**Comment by Shuunen** [comment]
just copy pasted it & it did the job, thanks :+1:  :smile:
