### ISSUE TITLE
Explanation on 'player' attribute

### ISSUE THREAD

**Issue by alastair-todd** [brandly/angular-youtube-embed#126]
I can't understand how to get a handle on individual players.

How to I watch for a specific event on a specific player with a dynamic id? Imagine 3 videos in a repeater (slider), all with unique ids.

This is a constant:
`var eventPrefix = 'youtube.player.';`

So wondering what the player="myplayer,player" is for, and why i can;t listen for e.g. 

` $scope.$on('myPlayer.player.playing'`

I'm ok with the catch all event, but I can't then work out which player triggerred it.

And there's no way (to my knowledge) to make the id dynamic, like an ng-id

I have an ugly hack where i add `data-type` to the directive element and check `player.a` which is a handle on the iframe element where I can read` data-type`...

**Comment by brandly** [comment]
sorry that the docs don't explain this well!

in the demo, i do something like this with the looping video. you can see the JS here: https://github.com/brandly/angular-youtube-embed/blob/master/src/demo/the.js#L37-L46

`looper.player` gets handed into the markup here: https://github.com/brandly/angular-youtube-embed/blob/master/src/demo/advanced.html#L13

that reference handed to `player` will be identical to what gets passed thru events, so you could compare like that.

here's how the directive picks the `id`: https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js#L139

so you could set a `player-id` attribute and compare with that.

hope this helps! let me know if there's anything else i can explain!

p.s. if this does make sense now and you'd like to help update the docs, send me a PR and i'd be happy to merge it in 😄

**Comment by brandly** [comment]
closing this but let me know if you have any more questions 🎆
