### ISSUE TITLE
Not able bind data to video-url tag in ng-repeat

### ISSUE THREAD

**Issue by iiitmahesh** [brandly/angular-youtube-embed#131]
#This not able bind data to video-url tag. 
it shows as it was in the console
 
```
<div ng-repeat="item in arrayList track by $index">
<youtube-video video-url="'{{item.videoURL}}'" player-width="'100%'" player-height="'250px'"></youtube-video>
</div>
```

**Comment by brandly** [comment]
here's an example of `video-url` inside an `ng-repeat`: https://github.com/brandly/angular-youtube-embed/issues/35

**Comment by iiitmahesh** [comment]
this syntax working for me 
`<youtube-video video-url="{{item.youtubeVideos[0].videoURL}}" player-width="'100%'" player-height="'250px'"></youtube-video>`

I have replaced above code with below following code

`<div ng-repeat="item in listOfData track by $index"> <h4>{{item.youtubeVideos[0].videoHeader}}</h4> <youtube-video video-url="item.youtubeVideos[0].videoURL" player-width="'100%'" player-height="'250px'"></youtube-video> `
