### ISSUE TITLE
How to get list of thumbnails

### ISSUE THREAD

**Issue by iiitmahesh** [brandly/angular-youtube-embed#132]
can I get video thumbnail using this angular-you tube-embed , if true please let me know
(Requirement is I wanna show list of videos, on clicking one item on the list it needed to be open full video on pop model )

Thank you

**Comment by brandly** [comment]
that's outside the scope of this project. it looks like it's fairly simple to get a thumbnail from youtube, however: http://stackoverflow.com/a/2068371/1614967

**Comment by algae514** [comment]
k thank you @brandly .

**Comment by iiitmahesh** [comment]
K Thank you @brandly
