### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by ParvejK** [brandly/angular-youtube-embed#133]
I am facing one problems "by2compare.js:677 Uncaught TypeError: Cannot read property 'indexOf' of undefined"

**Comment by ParvejK** [comment]
I am facing one problems "TypeError: core_1.NgModule is not a function
	    at eval (http://localhost:3000/app/app.module.js:20:16)
	    at Object.eval (http://localhost:3000/app/app.module.js:34:2)
	    at eval (http://localhost:3000/app/app.module.js:37:4)
	    at eval (http://localhost:3000/app/app.module.js:38:3)
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js(anonymous function) "

**Comment by brandly** [comment]
angular 2 is not supported currently! here's the original issue where we've discussed some things: https://github.com/brandly/angular-youtube-embed/issues/112

**Comment by brandly** [comment]
closing this issue in favor of #112
