### ISSUE TITLE
npm WARN youtubevideo@1.1.1 No repository field

### ISSUE THREAD

**Issue by Ased2235** [brandly/angular-youtube-embed#144]
Hi i'm trying to install but i got this error installing via `npm install --save angular-youtube-embed`
```
`-- angular-youtube-embed@1.3.1

npm WARN youtubevideo@1.1.1 No repository field.
npm WARN youtubevideo@1.1.1 No license field.
```
and this error via `bower install --save angular-youtube-mb`
```
bower invalid-meta  for:E:\app\My app\youtubevi
deo\bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digit
s, dots, dashes
bower ENOGIT        git is not installed or not in the PATH
```
can anyone help

**Comment by brandly** [comment]
it appears that _you_ are starting a project called `youtubevideo`. in your `package.json`, as the error message states, you don't have a repository/license field, and your `name` violates bower's rules.

these are only warning and should cause you no issues.

these warning are unrelated to this repo, so i'm closing this issue
