### ISSUE TITLE
switch between ui-router state causing error

### ISSUE THREAD

**Issue by speed-of-light** [brandly/angular-youtube-embed#15]
the ui-router configuration:

```
$stateProvider.state("a")
$stateProvider.state("b") //abstract
$stateProvider.state("b.c")
```

if state transition from "b.c" to "a" then it will causing the error

`TypeError: Cannot read property 'id' of null
    at O.g.destroy (https://s.ytimg.com/yts/jsbin/www-widgetapi-vflfilDmc/www-widgetapi.js:21:28)`

after this error, if I continue to change(or refill) the `video-id`  then

`TypeError: Cannot read property 'src' of null
    at O.g.J (https://s.ytimg.com/yts/jsbin/www-widgetapi-vflfilDmc/www-widgetapi.js:26:91)`

Any ideas?

**Comment by ladmerc** [comment]
Looks like this isn't fixed yet

**Comment by brandly** [comment]
@ladmerc if you want to provide a JSFiddle or something similar showing the issue, i can take a look. i was under the impression that #16 fixed the issue.

**Comment by nolafs** [comment]
Same issue here as well. 

TypeError: Cannot read property 'id' of null
    at X.g.P (www-widgetapi.js:89)
    at angular-youtube-embed.js:248
    at Scope.$get.Scope.$broadcast (ionic.bundle.js:30718)

**Comment by xlearner** [comment]
@speed-of-light can you tell me please how you put the `<youtube-video>` on the root state and how you  initialize it with a service ?
