### ISSUE TITLE
[Question] Does modestbranding parameter work?

### ISSUE THREAD

**Issue by AlvaroHerrero** [brandly/angular-youtube-embed#151]
Is it possible to set the modestbranding parameter in a Ionic app?
It is on the [parameter list](https://developers.google.com/youtube/player_parameters#Parameters), but setting it makes no effect and the youtube logo is still visible.

Thanks in advance.

**Comment by brandly** [comment]
yes! we pass parameters directly thru to the underlying YouTube Embed API. the `modestbranding` docs mention this tho:

> Note that a small YouTube text label will still display in the upper-right corner of a paused video when the user's mouse pointer hovers over the player.

**Comment by AlvaroHerrero** [comment]
Understood, the youtube logo is always visible when the video is not playing. 
Thank you!
