### ISSUE TITLE
youtube.player.playing returns only once

### ISSUE THREAD

**Issue by gururajmbhandarkar** [brandly/angular-youtube-embed#155]
Hi,

Using youtube.player.playing event to get time duration each second. But it happens to be executed only once. Is there any possible way to get time duration each second ?

i'm able to do this by using setInterval function inside playing event. But is there any workaround with the package?

Please revert if i'm not clear. Cheers ;)

**Comment by brandly** [comment]
hey

this has been discussed: https://github.com/brandly/angular-youtube-embed/issues/80#issuecomment-205837616

this package doesn't really provide an out-of-the-box solution. good luck!
