### ISSUE TITLE
API event messages are not received

### ISSUE THREAD

**Issue by rushdykamel** [brandly/angular-youtube-embed#165]
It seems that only recently, event messages stopped to be received from **iframe_API**.. after debugging I found that the directive overrides Youtube player object ID.. which it seems preventing the API from sending messages to the client. after removing that, it worked fine..
I created this PR to fix it https://github.com/brandly/angular-youtube-embed/pull/164

**Comment by LoyalPotato** [comment]
Worked for me. Also had some problems where the events weren't being triggered.
Could you tell me how you went about debugging the problem?

**Comment by rushdykamel** [comment]
I'm glad it worked for you.. and yes it was blocking all the events...
I started debugging with using native JS to call youtube iframe API.. then created my own directive and used bits and pieces from angular-youtube-embed library.. trying to find out what makes it break! and it was that line..

**Comment by galdil** [comment]
Will someone approve this fix?
Or u have just cloned the library?

**Comment by brandly** [comment]
@rushdykamel thanks! Good work!

How do you all use this library? Install from `npm`? Copy it into some `vendor` directory?

I haven't touched this repo in a long time, so I'll have to figure out how to get a new release published. Bear with me!

**Comment by rushdykamel** [comment]
Hi @brandly 
Thank you for merging the PR.
Yes, I use `npm` to install the library.. you will need to publish a new NPM version.

**Comment by brandly** [comment]
`v1.3.2` out now ✨
