### ISSUE TITLE
Invalid isolate scope definition

### ISSUE THREAD

**Issue by hypervillain** [brandly/angular-youtube-embed#29]
Hello,

I tried to use the module inside a chrome extension using angular and got this error:
"Error: Invalid isolate scope definition for directive youtubeVideo: =? at Error (native)"

Also, "Refused to load the script 'https://www.youtube.com/iframe_api' because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:" gets printed, but not sure if it is related.

Any idea ?

**Comment by theashishranjan** [comment]
Getting the same error, could you provide some more insight into what you exactly did? some code snippet would be useful.

**Comment by brandly** [comment]
@THook, could you help Ashish out? i'm curious to know what's going on here too.

it might be related to #39, so i should probably go deal with that.

**Comment by theashishranjan** [comment]
Turns out I get the error only when I am using angular 1.0.8, and I am restricted to that version.

**Comment by brandly** [comment]
oh yeah, i think optional attributes were introduced sometime after `1.0.x`, so this directive doesn't support your version.

if you took this code and modified it a bit to directly support your particular use case, i bet you can get it working, but the `=?` helps this code support a wider range of use cases.

best of luck :star2:
