### ISSUE TITLE
player attribute isn't populated when ng-if is used

### ISSUE THREAD

**Issue by Soviut** [brandly/angular-youtube-embed#34]
I have several posters that, when clicked, replace themselves with a `youtube-video` directives. It uses an `ng-if` to prevent any unnecessary player initialization on page load. The problem is, the `player` attribute remains undefined once the `ng-if` condition becomes true and is digested.
```
<youtube-video video-id="..." player="player" ng-if="started">
```

**Comment by brandly** [comment]
closing this for now. let me know if you have more details about this :star2:

**Comment by olive75** [comment]
Hello, I think I face a similar problem with the following snippet. The player was not available outside of the child scope created by the ng-if. 
```
<div ng-if="topic.type === 2">
                <youtube-video player="player" video-id="topic.id">
                </youtube-video>
              </div>
              
              <a href="" class="time" ng-click="player.seekTo(120, true)">
                Go to 2 minutes
              </a>
```
The simpliest solution was to add the player object as a property of the topic object. I found some explanation here http://stackoverflow.com/a/21512751/3542165 
```
<div ng-if="topic.type === 2">
                <youtube-video player="topic.player" video-id="topic.id">
                </youtube-video>
              </div>
              
              <a href="" class="time" ng-click="topic.player.seekTo(120, true)">
                Go to 2 minutes
              </a>
```
May be some words on how to access the player object from any scope  would be helpful in the readme?
