### ISSUE TITLE
is it me or it is simply not possible to have this directive in a loop ?

### ISSUE THREAD

**Issue by docteurklein** [brandly/angular-youtube-embed#35]
imagine:

```
$scope.urls = [ 'url-1', 'url-2' ]; 

-----------------

<div ng-repeat="url in urls">
    <youtube-video video-url="{{ url }}">
```

**Comment by iiitmahesh** [comment]
this syntax working for me 
`<youtube-video video-url="{{item.youtubeVideos[0].videoURL}}" player-width="'100%'" player-height="'250px'"></youtube-video>`

I have replaced above code with below following code  

`<div ng-repeat="item in listOfData track by $index">
	<h4>{{item.youtubeVideos[0].videoHeader}}</h4>		
<youtube-video video-url="item.youtubeVideos[0].videoURL" player-width="'100%'" player-height="'250px'"></youtube-video>
	`
