### ISSUE TITLE
TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by arLevi** [brandly/angular-youtube-embed#36]
not sure from where the issue is coming from.
the strange thing is that there's no error in Firefox & Safari but only in Chrome (v39) - and the video doesn't load.

Your demo does works on Chrome, so I'm guessing something in the code bothering it, I'm just not sure from where to start, because the error points only to Angular

```
TypeError: Cannot read property 'childNodes' of undefined
    at g (http://domain.com/js/angular.min.js:51:321)
    at g (http://domain.com/js/angular.min.js:51:316)
    at g (http://domain.com/js/angular.min.js:51:316)
    at http://domain.com/js/angular.min.js:50:414
    at http://domain.com/js/angular.min.js:18:8
    at k.$eval (http://domain.com/js/angular.min.js:124:325)
    at k.$apply (http://domain.com/js/angular.min.js:125:6)
    at http://domain.com/js/angular.min.js:17:479
    at Object.e [as invoke] (http://domain.com/js/angular.min.js:36:365)
    at d (http://domain.com/js/angular.min.js:17:400)
```

When I remove the <youtube tag - the error goes away.
I'm also using ng-facebook, so I'm using Angular 1.2.27

Just wanted to know if you have something in mind, it will take me a while to debug it...

**Comment by brandly** [comment]
i'm using chrome. the first set of code you provided seems to run just fine on my end.

in the second set of code, moving the `script` tags into the head prevented the issue from occurring.

i hope you got things working! i'm going to close this for now, but let me know if you run into more trouble

**Comment by arLevi** [comment]
Thanks, actually by the time I needed to get this resolved, I found that there's an updated version of this lib, so I updated, and added the <script ... iframe></script> thing ... ( which I didn't see before )
it actually solved my problem :)

**Comment by brandly** [comment]
Glad you got it working!

**Comment by Jefftronn** [comment]
What was the lib?
