### ISSUE TITLE
how to reference & control specific player from Controller?

### ISSUE THREAD

**Issue by auching** [brandly/angular-youtube-embed#40]
i tried below but it throws errors:

in html:
```html
<youtube-video video-id="'sMKoNBRZM1M'" player="bestPlayer"></youtube-video>
```

in my controller:

```js
$scope.bestPlayer.playVideo();
```

**Comment by brandly** [comment]
where are you calling `$scope.bestPlayer.playVideo();`?

`$scope.bestPlayer` won't be defined immediately. you'll have to wait til the player gets initialized.

if you're trying to automatically play a video, use [player parameters](https://github.com/brandly/angular-youtube-embed#player-parameters)

maybe taking a look at the demo [HTML](https://github.com/brandly/angular-youtube-embed/blob/cb444fced3c212f5b4a7af5e1c29ac824520943b/src/demo/advanced.html#L15-L20) and [JS](https://github.com/brandly/angular-youtube-embed/blob/cb444fced3c212f5b4a7af5e1c29ac824520943b/src/demo/the.js#L50-L56) will help

let me know :rainbow:
