### ISSUE TITLE
infinite $digest loop

### ISSUE THREAD

**Issue by CptCompiler** [brandly/angular-youtube-embed#43]
Hi matt,

I really like your angular youtube player directive! 
I am relatively new to angular. I dont really know if it is a bug or whatever.

I realised that the following function produces an infinite $digest loop:

```javascript
            function applyBroadcast () {
                var args = Array.prototype.slice.call(arguments);
                scope.$apply(function () {
                    scope.$emit.apply(scope, args);
                });
            }
```

Do you know a way to fix this issue?

**Comment by brandly** [comment]
could you provide some context, like what version of angular you're using and what your code looks like? thanks!

**Comment by CptCompiler** [comment]
Hi Matt, 
I just realised that the error is on my side. Please close this issue.
Sorry for the inconvenience.

**Comment by brandly** [comment]
glad you figured it out! no worries
