### ISSUE TITLE
Question: how can I detect when the timeline is manipulated?

### ISSUE THREAD

**Issue by germanger** [brandly/angular-youtube-embed#50]
Given this scenario:

- Player is complety loaded (100% of the video is already loaded)
- Player is in state "playing" (it already fired that event some time ago)

If the user clicks in the timeline (eg: in the middle, or 3/4 of it), the player will skip to that part without firing any events (no buffering because its already buffered, not playing because it is already playing).

How can I detect this situation? 
Is "watching" the only way?

**Comment by brandly** [comment]
i'm not sure!

depending on your needs, you could potentially build your own progress bar and call [`seekTo`](https://developers.google.com/youtube/iframe_api_reference#seekTo) when it's clicked. you can use [player parameters](https://github.com/brandly/angular-youtube-embed#player-parameters) to hide the standard controls

you could put a `$watch` on [`getCurrentTime()`](https://developers.google.com/youtube/iframe_api_reference#getCurrentTime), but that seems fragile

let me know if you find a better way!
