### ISSUE TITLE
Change the scr of video dynamically

### ISSUE THREAD

**Issue by idoviron** [brandly/angular-youtube-embed#52]
I've just tried to change theBestVideo variable but no effect on it.

**Comment by ToothpickFactory** [comment]
Running into the same issue. I would be interested in some guidance here as well.

**Comment by markbgh** [comment]
Same here. I was really excited to find this and was going insane watching my scope update but not having it be reflected in the video.

**Comment by ToothpickFactory** [comment]
Hey guys I found a way to change the videos dynamically. The player object has a function on it called "cueVideoById()". You just need to pass in the videoID into it and it changes the video. In my controller a wrote a function that looks like this, $scope.changeVideo = function(player, videoID){
        player.cueVideoById(videoID);
        player.playVideo();
    }

I hope this helps! I can go into more detail if this did not make sense.

**Comment by ToothpickFactory** [comment]
If I get super ambitions I will do a fork and build this in.

**Comment by brandly** [comment]
thanks for the help! #46 is probably the true goal but, for now, things are working again :star2: 

[v1.0.2](https://github.com/brandly/angular-youtube-embed/releases/tag/v1.0.2)

**Comment by ToothpickFactory** [comment]
Awesome! Glad we could be of help ^^

**Comment by markbgh** [comment]
Excellent! Thanks!
