### ISSUE TITLE
iOS home screen web app

### ISSUE THREAD

**Issue by konsumer** [brandly/angular-youtube-embed#58]
If I make a homescreen bookmark from the webapp (which will open my app in a borderless web window) when the video is loaded, it spawns the youtube app to play it.

[this](http://stackoverflow.com/questions/25972600/ios-8-embedded-youtube-in-html-web-app-fails) is related.

If I manually make an embed that looks like this, using `$sce.trustAsResourceUrl($scope.videoURL)`, it works:

```html
<iframe width="100%" height="300" src="{{videoURL}}" frameborder="0" allowfullscreen></iframe>
```

but I must use `https://www.youtube-nocookie.com/embed/VIDEOID` and I don't get any of the event callbacks.

to reproduce:

* visit [this demo](http://ngyoutubeios.bitballoon.com/) on an iOS device
* Add to home screen (under the bookmark menu)
* open link from homescreen

Maybe there isn't a fix, but it seems like it should work if the youtube iframe API allows `-nocookie` domain.

**Comment by brandly** [comment]
hey! i just tried this on my iPhone, and it's definitely redirecting me to the YouTube app.

i'm not sure of a fix here. ultimately, we're just handing the underlying library [a video id](https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js#L175). in the case of using a `video-url`, we're [manually extracting the id](https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js#L213). so it doesn't look like there's a way to force the `-nocookie` domain.

if you see something i'm missing, let me know!

**Comment by konsumer** [comment]
I think it might require a fix to the underlying library or possibly just take the upstream javascript and search & replace for the domain.

**Comment by sguilly** [comment]
If i add this to my app config

```javascript
.config(function($sceDelegateProvider) {

    $sceDelegateProvider.resourceUrlWhitelist([
      // Allow same origin resource loads.
      'self',
      // Allow loading from our assets domain.  Notice the difference between * and **.
      'https://www.youtube-nocookie.com/**']);
...
```
and this line in angular-youtube-embed.js

```javascript
angular.module('youtube-embed', ['ng'])
.service ('youtubeEmbedUtils', ['$window', '$rootScope', function ($window, $rootScope, $sceDelegateProvider) {

...

// Add this line
YTConfig.host = 'https://www.youtube-nocookie.com';

return Service;
}])
```
the video is well embedded by i have no sound...

The same web app in the safari browser works well.

**Comment by konsumer** [comment]
@sguilly: I used your trick, and got it [working here](http://underwriter-cavities-40755.bitballoon.com). On mine it has sound.

**Comment by brandly** [comment]
thanks a lot for the help, @sguilly! glad it's work for you, @konsumer

**Comment by konsumer** [comment]
I might make sense to put this in the README:

If you're making an iOS Home-screen page, you should make your code look like this to use a host that doesn't force you to use the Youtube app to play the video:
```javascript
YTConfig.host = 'https://www.youtube-nocookie.com';
  
  angular.module('app', ['youtube-embed'])
  .controller('Demo', function($scope, $sce){
    $scope.theBestVideo = 'sMKoNBRZM1M';
  });
```

**Comment by brandly** [comment]
you didn't need the `$sceDelegateProvider.resourceUrlWhitelist` stuff?

also, do you know _why_ the `nocookie` domain doesn't redirect to the YouTube app? any insight would be helpful. i'd really like this in the README, but i think it'd be nice to provide some explanation instead of just being like "here's some magic"

thanks again :star:

**Comment by konsumer** [comment]
Nope, without the delegate stuff, just like yours does. Nocookie domain is just a non YouTube domain that mirrors it. ios has hooks to load the app when you open a URL that looks like a YouTube video. I tested my second demo on an iPad, and it works. It's not magic, I just wasn't aware that you could set the baseurl for the YouTube lib.
