### ISSUE TITLE
cast_sender.js error

### ISSUE THREAD

**Issue by celsomtrindade** [brandly/angular-youtube-embed#67]
I'm using it and sice i inserted in my webapp i got this error: 
`GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js ` 

It appears a couple of times and i've included both files, youtube and the directive, just like the example. I'm using a video-url with `AngularJs 1.4.3`.

What may be wrong?

***index***

	
	<script src="https://www.youtube.com/iframe_api"></script>
	<script type="text/javascript" src="dist/lib/ngYoutube.min.js"></script>

***html***

	<div class="embed-responsive embed-responsive-16by9">
		<youtube-video class="embed-responsive-item" video-url="lookVideo"></youtube-video>
	</div>

***ctrl***

	$scope.lookVideo = 'https://www.youtube.com/watch?v=[myvideocode]'; //I'm using a correct url, but i changed because of client restrictions

**Edit**: Everything is working fine. But i have this error showing up a couple of times, and only in the page where the video appears.

**Comment by qubird** [comment]
This looks like a problem with a chrome extension, not sure it relates to
angular yt embed

**Comment by brandly** [comment]
this appears relevant: http://stackoverflow.com/a/27448688/1614967

so it could be related to the underlying `https://www.youtube.com/iframe_api`, but it doesn't look directly related to code i have control over

**Comment by celsomtrindade** [comment]
Since it's working everything ok and I didn't found any other related issue about this, I tought it would be good to report this issue, even thought it's not direct releated with the directive (which i only know now). In firefox it also have some similar errors. This is mine: `Error: WebGL: getParameter: parameter: invalid enum value <enum 0x9246>`

**Comment by brandly** [comment]
@celsomtrindade thanks! i'll leave this open and see if anyone comes up a solution. i'm glad it's working, at least :smile:

**Comment by brandly** [comment]
looks like this has to do with the underlying youtube library looking for a chromecast extension: https://code.google.com/p/google-cast-sdk/issues/detail?id=309
