### ISSUE TITLE
Push to NPM 1.1.0

### ISSUE THREAD

**Issue by okhomenko** [brandly/angular-youtube-embed#69]
Looks like latest on NPM is 1.0.3. 

Could you please push 1.1.0 to NPM?

Thanks, Alex

**Comment by brandly** [comment]
hey! here's the problem: i originally only published this on `bower`, and @Mosho1 forked this project and published it to `npm`. i got everything in place on this repo, such that it's ready to publish, but i'm currently hitting a conflict

if @Mosho1 does an `npm unpublish`, i'll get the latest published. i've tried messaging about it [here](https://github.com/Mosho1/angular-youtube-embed/commit/b7f6ecf956f2bc4fff955e3d8e4d4ce316f1172b), but i'm glad you've reminded me! thanks

**Comment by brandly** [comment]
actually, it looks like `angular-youtube-embed` was available on `npm`, so i've [published it under that name](https://www.npmjs.com/package/angular-youtube-embed). thanks again!

**Comment by okhomenko** [comment]
Great job, thank you so much.
