### ISSUE TITLE
Audio volume on iOS

### ISSUE THREAD

**Issue by vandres** [brandly/angular-youtube-embed#73]
This may not be related to your plugin, but perhaps you know a solution.

When having the phone muted on iOS (hardware button) the audio of a video in a PhoneGap app is not being played. When opening a video in the Youtube app or in mobile Safari, the audio is playing.

**Comment by RopoMen** [comment]
Could this be some kind of iOS application permission issue?

**Comment by vandres** [comment]
I think I found the solution. When installing this plugin, all works fine: https://github.com/EddyVerbruggen/cordova-plugin-backgroundaudio It is related to this topic: http://stackoverflow.com/questions/3740528/play-sound-on-iphone-even-in-silent-mode The plugin makes all the work with adapting the objective C Code

This Issue can be closed. Thank you for your response

**Comment by brandly** [comment]
thanks for the help @RopoMen!

i'm glad you got it working @vandres! thanks for the update :star:
