### ISSUE TITLE
angular expression inside video-id not working

### ISSUE THREAD

**Issue by respectYourNeighbour** [brandly/angular-youtube-embed#81]
<youtube-video class="embed-responsive-item ng-isolate-scope" video-id="{{melody}}"></youtube-video>

Im trying to insert inside 'video-id' angular expression 'video-id = {{melody}}' and I get an [$parse:syntax] error.
In controller I have $scope.melody ='kkJXmcMtPws';

**Comment by brandly** [comment]
everything handed to `video-id` is treated as an expression. as shown [in the docs](https://github.com/brandly/angular-youtube-embed#can-i-use-it)...

```html
<youtube-video video-id="melody"></youtube-video>
```

will work

**Comment by respectYourNeighbour** [comment]
Hey, awesome!
I was using with {{ ...  }}, but no need for curly brackets. Thanks. It works.

**Comment by brandly** [comment]
:+1: :+1:

**Comment by bartwttewaall** [comment]
Hi Brandly, I'd like to contribute to this issue.
After adding your directive to my app I just blank-minded pasted the id into the video-id attribute as a string and nothing happened. It struck me as odd that this was not default behaviour.
After changing the directive's scope's video-id and video-url parameters to "@?" I got my expected result: set the value directly with a string or bind to an expression with double curly braces. What motivated you to set it to "=?" exactly? Maybe I could learn something here ;)
