### ISSUE TITLE
New version of chrome 46.0.2490.71 m

### ISSUE THREAD

**Issue by blonboll** [brandly/angular-youtube-embed#82]
I encountered a problem in the new version Chrome 46.0.2490.71 m

https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/chrome/rwodNFE9gUI/EMWHTW8pCQAJ

How to solve it? Or some workaround? I am using autoplay to play another song after one was finished.

Ths so much.

**Comment by brandly** [comment]
as far as i know, there's no way around this. i'm closing this issue in favor of #84. maybe someone will come through with some suggestions :star2:
