### ISSUE TITLE
changing player-vars model

### ISSUE THREAD

**Issue by MurWade** [brandly/angular-youtube-embed#83]
i have a button that toggles the loop option in the player-vars model but doesnt take effect unless it is loaded the first time. how can i make it so it is 2 way binding

**Comment by brandly** [comment]
unfortunately, with the underlying YouTube API, i'm not sure there's good way to make `player-vars` values update live

however, instead of the `loop` option, you could do something like this

```js
$scope.$on('youtube.player.ended', function ($event, player) {
  if (options.shouldLoop) {
    // play it again
    player.playVideo()
  }
});
```

does that work for you?

**Comment by MurWade** [comment]
ya i do a similar thing. but i write my function inside the angular-youtube-embed.js. if you put this inside the library it wuld make it easier . i have done my own fork though. 

              function onPlayerStateChange(event) {
                    /*.......*/
                    if (state == 'ended') {
                        if(scope.playerVars.loop) {
                            
                        scope.player.playVideo();
                        }
                    }                    
                    /*.......*/

                }

**Comment by brandly** [comment]
i'd recommend doing it outside the library, since you won't be able to take advantage of future versions of this library and bug fixes. i'm glad you got it working tho!
