### ISSUE TITLE
Style the youtube controller

### ISSUE THREAD

**Issue by kasszz** [brandly/angular-youtube-embed#85]
Is it possible to style the youtube controller?

**Comment by brandly** [comment]
you can [set the color](https://developers.google.com/youtube/player_parameters#color) via `player-vars`. otherwise, you can build controls for scratch, like the "custom controls" example [found here](http://brandly.github.io/angular-youtube-embed/#/advanced)

**Comment by kasszz** [comment]
Ty :)
