### ISSUE TITLE
Dynamically change player start and end limits on same video?

### ISSUE THREAD

**Issue by diegoaguilar** [brandly/angular-youtube-embed#86]
While displaying a certain video, I'm setting and picking some time intervals to tag (this is my app logic) then I'd like to add *additional nested* tags to those video time intervals.

I'd like to prevent player to seek before or after the time start and end seconds of the selected interval. Any suggestions for this?

**Comment by jeffersonrpn** [comment]
I'm having the same problem. When I change the video ID dinamically, the interval of start and end are lost.

**Comment by brandly** [comment]
@jeffersonrpn could you provide a [JSFiddle](http://jsfiddle.com/) or something similar documenting the issue?

**Comment by brandly** [comment]
i'm closing this issue for now, until further explanation 🌟
