### ISSUE TITLE
(couldn't find file 'ng-youtube-embed' with type 'application/javascript'):

### ISSUE THREAD

**Issue by alucardu** [brandly/angular-youtube-embed#88]
I've install the package through `bower install ng-youtube-embed --save` and then I need to add it to my project. So I add `//= require ng-youtube-embed` to my application.js file. But then when I open the bowser I get an error,

    Completed 500 Internal Server Error in 123ms (ActiveRecord: 0.1ms)

    ActionView::Template::Error (couldn't find file 'ng-youtube-embed' with type 'application/javascript'):
        42: 
        43: 
        44:       = stylesheet_link_tag    'application', media: 'all'
        45:       = javascript_include_tag 'application'
        46:       = csrf_meta_tags
      app/assets/javascripts/application.js:12
      app/views/layouts/application.html.haml:45:in `_app_views_layouts_application_html_haml__194702097893876376_70014477921800'
      app/controllers/application_controller.rb:6:in `angular'

Hm, by placing the `angular-youtube-embed.js` file in my vendor/javascripts and then do `//= require angular-youtube-embed.js` in the appication.js does load the files correctly.

**Comment by brandly** [comment]
[this project's bower package](https://github.com/brandly/angular-youtube-embed/blob/master/bower.json#L2) is `angular-youtube-mb`! you might be looking for another for another project, or maybe you accidentally installed the wrong one

hope you get it working!

**Comment by alucardu** [comment]
Wauw! I'm sorry I totally posted my issue in the wrong project!

**Comment by brandly** [comment]
i [recently removed it](https://github.com/brandly/angular-youtube-embed/commit/bfbd6ed8b0050c095b3063b7c635de0275ffa9c5#diff-04c6e90faac2675aa89e2176d2eec7d8L12), largely due to [this announcement](https://twitter.com/nachocoloma/status/663622545162280960). since then, they [announced this](https://twitter.com/bower/status/667337272270970880), so i should probably put it back
