### ISSUE TITLE
Dynamically change value of $scope.theBestVideo

### ISSUE THREAD

**Issue by alucardu** [brandly/angular-youtube-embed#89]
I am wondering if it is possible to change the value (and thus the trailer) of `$scope.theBestVideo` from within a ng-click action.

**Comment by brandly** [comment]
at [the bottom of this page](http://brandly.github.io/angular-youtube-embed/#/advanced), you can see an example of a video id changing with an `ng-click`.

[the JS is here](https://github.com/brandly/angular-youtube-embed/blob/master/src/demo/the.js#L73-L84), and [the markup is here](https://github.com/brandly/angular-youtube-embed/blob/master/src/demo/advanced.html#L47-L55)
