### ISSUE TITLE
Package version mismatch

### ISSUE THREAD

**Issue by piotrd** [brandly/angular-youtube-embed#90]
Hi,

I noticed that, although `package.json` and npm itself reports that I have installed `angular-youtube-embed` version 1.1.1, when I look inside the `dist/angular-youtube-embed.min.js`, it shows version 1.1.0. 

So which version is actually packed in the latest package?

**Comment by brandly** [comment]
looks like i forgot to update `dist/` until after i had published v1.1.1 to npm. however, if you're using some form of CommonJS, like browserify or webpack, it'll directly hit `src/angular-youtube-embed.js` which is truly at v1.1.1

let me know if this works for you :star:

**Comment by piotrd** [comment]
Yeah, you're right. I'm using browserify and it does use the version from `/src`. Thanks.
