### ISSUE TITLE
Not working in Electron

### ISSUE THREAD

**Issue by diegoaguilar** [brandly/angular-youtube-embed#91]
I tried to load it inside an Electron app, I properly added Angular's app module, dependencies and a controller, also the CSS classes for responsive video, just any video is being rendered:

This is markup:

```html
<!DOCTYPE html>
<html ng-app='FinalCutApp'>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <!-- bower:css -->
    <link rel="stylesheet" href="bower_components/animate.css/animate.css" />
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="bower_components/angular-loading-bar/build/loading-bar.css" />
    <!-- endbower -->
    <!-- inject:css -->
    <link rel="stylesheet" href="public/css/index.css">
    <!-- endinject -->
  </head>
  <body ng-controller='IntroController'>
    <!-- bower:js -->
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.js"></script>
    <script src="bower_components/angular-loading-bar/build/loading-bar.js"></script>
    <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
    <script src="bower_components/ngstorage/ngStorage.js"></script>
    <script src="bower_components/angular-youtube-mb/src/angular-youtube-embed.js"></script>
    <script src="bower_components/angular-animate/angular-animate.js"></script>
    <!-- endbower -->

    <!-- inject:js -->
    <script type="text/javascript" src="public/js/angular/random.js"></script>
    <script type="text/javascript" src="public/js/angular/controllers/IntroController.js"></script>
    <!-- endinject   -->
    <div class="container">
      <h1>Final Cut</h1>
      <div class="embed-responsive embed-responsive-16by9">
        <youtube-video class="embed-responsive-item" video-id="youtubeId"></youtube-video>
      </div>
    </div>
</html>
```

Something curious is that an odd class is being added to the `youtube-video` element and size properties are set to `0px`:

![image](https://cloud.githubusercontent.com/assets/2483678/11756528/2b81de90-a020-11e5-8875-20b306e533e9.png)

**Comment by diegoaguilar** [comment]
I just would like to know is there's any either Angular's or Electron's reason not to get working, otherwise this can get closed

**Comment by brandly** [comment]
are there any errors being thrown? the way this directive works, it should replace the `<youtube-video>` with an `<iframe>`, so if you're still seeing `<youtube-video>`, i'd guess the directive is somehow not being included and isn't defined within your app.

i haven't used electron, but to determine if it's something electron-specific, you could try running the code in a browser and see if it works

**Comment by diegoaguilar** [comment]
Module (`'youtube-embed'`) is included, so the controller. Any debug mode or trick to be included?

**Comment by diegoaguilar** [comment]
Not working at browser neither. Btw I've imported it from bower (for the first time)

**Comment by diegoaguilar** [comment]
@brandly I've added you as collaborator to the project, just to help debug it, I'm almost sure now that it's on my side. Closing the issue for now.

**Comment by diegoaguilar** [comment]
Ok, found the issue myself:

I was not following one of the very first steps shown at README:

```html
<!-- Include YT library and this directive -->
<script src="https://www.youtube.com/iframe_api"></script>
<script src="angular-youtube-embed.js"></script>
```

I was not importing youtube's iframe API, I changed the title of the issue to help others with same mistake notice it faster

**Comment by brandly** [comment]
glad you got it working!

**Comment by ashish367** [comment]
hey i have included iframe api also but showing <youtube-video > i think its not compiling

**Comment by brandly** [comment]
@ashish367 what error message do you see?

**Comment by ashish367** [comment]
Helllo Matthew Brandly,
Thanks for giving time and reaching me, I have used your youtube directive
in my project but i face this issue
*www-widgetapi.js:27 Failed to execute 'postMessage' on 'DOMWindow': The
target origin provided ('https://www.youtube.com
<https://www.youtube.com>') does not match the recipient window's origin
('http://localhost:8080').*


*Regards,*
Ashish Yadav
CM Software Services Pvt. Ltd.
Email: ashish.yadav@cmss.in
Mobile: +91 9702099924
Website: www.cmss.in

**Comment by ashish367** [comment]
Hello,
I also want to know how and when will autoplay will work and is there any
other option to autoplay i need it asap


*Regards,*
Ashish Yadav
CM Software Services Pvt. Ltd.
Email: ashish.yadav@cmss.in
Mobile: +91 9702099924
Website: www.cmss.in

**Comment by brandly** [comment]
@ashish367 the "Failed to execute 'postMessage' on 'DOMWindow'" has been discussed a bit here: #62

`autoplay` appears to be working on the demo here: http://brandly.github.io/angular-youtube-embed/#/advanced

**Comment by ashish367** [comment]
Hello Matthew Brandy,
Thanks but Iam asking for autoplay on mobile devices
As u siad it clearly "*autoplay won't work on mobile devices :(*" but how
should i solve this issue any idea


*Regards,*
Ashish Yadav
CM Software Services Pvt. Ltd.
Email: ashish.yadav@cmss.in
Mobile: +91 9702099924
Website: www.cmss.in

**Comment by brandly** [comment]
as far as i understand, it's a platform restriction that's outside my control. this entire directive is a small wrapper on top of the official YouTube embed library. i'm passing the `autoplay` option directly through to them, so if things change and YouTube is able to autoplay on mobile devices, it should work. until then, i'm not sure if there's any workaround.
