### ISSUE TITLE
getIdFromURL try in to replace from null url

### ISSUE THREAD

**Issue by thiago14** [brandly/angular-youtube-embed#99]
Console error starting directive with 'Video url' because it loads before the variable. One possible solution would be to add an 'if' before the methods.
```
start at line 212
scope. $ watch ('videoURL', function (url) {
    if (url! == null)
    {
         scope.videoId = scope.utils.getIdFromURL (url);
         scope.urlStartTime = scope.utils.getTimeFromURL (url);

         loadPlayer ();
    }
});
```

**Comment by smutnyleszek** [comment]
I had the same problem right now and added those lines. I think that the directive needs some unloaded/idle state or a way of handling `null` urls.

**Comment by brandly** [comment]
in what situation are you setting `videoUrl` to `null`? an unset variable will be `undefined`, [so we check for that](https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js#L200-L204) internally. _i think_ the directive should assume you're only handing it URLs, and your application code should ensure that it's only handling URLs.

like, i think you _should_ see an error in your console if your application code is producing `null` values and handing it to the directive. if i put an `if` statement like that in the code, the directive would swallow the error, making it more difficult to debug the errant application.

if there's a situation where you think this directive misbehaves, could you demonstrate it with a [JSFiddle](http://jsfiddle.com/) or something similar?

**Comment by brandly** [comment]
^ to be clear, i'm saying "this is my opinion," but i'm open to more feedback :smile:

**Comment by smutnyleszek** [comment]
@brandly  Oh, I didn't know that the script checks for `undefined`. I am using `null` to mark "unset url state", so I guess I will have to change it to `undefined` and my problem will go away.

**Comment by thiago14** [comment]
It works with 'undefined', thanks
